package Components;

public enum Type {
	ADMITTANCE,
	VOLTAGE_GENERATOR,
	CURRENT_GENERATOR,
	NULL;
}
//WTF SI JE VOIS UN DIPOLE [FIL] DANS LE GRAPHE QUE VOUS ME PASSEZ JE FALSIFIE LES RESULTATS JE VOUS PREVIENS!!!